=== hoocen/gsnaker/src/test/resources/test/task/simple/gsnaker.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/gsnaker" xmlns:tns="http://www.example.org/gsnaker" elementFormDefault="qualified">
	<xs:element name="process">
		<xs:complexType>
			<xs:choice>
				<xs:element name="start">
					<xs:complexType>
						<xs:choice>
							<xs:element name="transition" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="to" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="name" type="xs:string"></xs:attribute>
									<xs:attribute name="go" type="xs:string"></xs:attribute>
									<xs:attribute name="offset" type="xs:string"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
						<xs:attribute name="displayName" type="xs:string"></xs:attribute>
						<xs:attribute name="layout" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="task" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="transition" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="to" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="name" type="xs:string"></xs:attribute>
									<xs:attribute name="go" type="xs:string"></xs:attribute>
									<xs:attribute name="offset" type="xs:string"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
						<xs:attribute name="displayName" type="xs:string"></xs:attribute>
						<xs:attribute name="assignee" type="xs:string"></xs:attribute>
						<xs:attribute name="performType" type="xs:string"></xs:attribute>
						<xs:attribute name="layout" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="decision" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="transition" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="to" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="expr" type="xs:string"></xs:attribute>
									<xs:attribute name="name" type="xs:string"></xs:attribute>
									<xs:attribute name="go" type="xs:string"></xs:attribute>
									<xs:attribute name="offset" type="xs:string"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
						<xs:attribute name="expr" type="xs:string"></xs:attribute>
						<xs:attribute name="displayName" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="end">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
						<xs:attribute name="displayName" type="xs:string"></xs:attribute>
						<xs:attribute name="layout" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
			<xs:attribute name="displayName" type="xs:string"></xs:attribute>
			<xs:attribute name="version" type="xs:integer"></xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hoocen/gsnaker/src/test/resources/test/task/simple/decision.snaker.xml
<?xml version="1.0" encoding="UTF-8"?>
<process  xmlns="http://www.example.org/gsnaker"  
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
      xsi:noNamespaceSchemaLocation="gsnaker.xsd"
      displayName="简单表达式流程" name="expression">
      <start name="start1">
      	<transition name="ts1" to="task1"/>
      </start>
      <task name="task1" displayName="审批">
      	<transition name="ts2" to="decision1"/>
      </task>
      <decision name="decision1" displayName="审批结果">
      	<transition name="ts3" displayName="通过" expr="${result}" to="end1"/>
      	<transition name="ts4" displayName="驳回" expr="${!result}" to="task2"/>
      </decision>
      <task name="task2" displayName="修正">
      	<transition name="ts5" to="decision2"/>
      </task>
      <decision name="decision2" expr="${result}" displayName="审批结果">
      	<transition name="true" displayName="修改"  to="task1"/>
      	<transition name="false" displayName="取消" to="end1"/>
      </decision>
      <end name="end1"/>
</process>
